#matrix:
#  include:
#    - env: BUILD="swift build"
#      os: linux
#    - env: BUILD="swift build -Xlinker -L/usr/local/lib" SWIFT_VERSION=swift-4.0-RELEASE
#      os: osx
#  allow_failures:
#    - os: osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:16.04 SWIFT_SNAPSHOT=4.0
    - os: osx
      osx_image: xcode9
      sudo: required

script:
  - ./build.sh
