matrix:
  include:
    - env: BUILD="swift build"
      os: linux
    - env: BUILD="swift build -Xlinker -L/usr/local/lib"
      os: osx
  allow_failures:
    - os: osx

language: objective-c
sudo: required
dist: trusty
osx_image: xcode9

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mysql; fi

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - $BUILD
