matrix:
  include:
    - os: linux
    - os: osx
  allow_failures:
    - os: osx

language: objective-c
sudo: required
dist: trusty
osx_image: xcode9

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then install mysql; fi

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift build; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swift build -Xlinker -L/usr/loal/lib; fi
