matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
       - docker

script:
  - docker pull letsspeak/stock-ci:latest
  - export CID=$(docker run -d letsspeak/stock-ci:latest)
  - docker ps -a
  - docker cp . $CID:/var/stock
  - docker exec $CID bash -c 'OPTIMIZE=1 make deps all'

notifications:
  email:
    on_success: never
    on_failure: always
