#matrix:
#  include:
#    - env: BUILD="swift build"
#      os: linux
#    - env: BUILD="swift build -Xlinker -L/usr/local/lib" SWIFT_VERSION=swift-4.0-RELEASE
#      os: osx
#  allow_failures:
#    - os: osx
os: linux

language: generic
sudo: required
dist: trusty
#osx_image: xcode9

before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mysql; fi

install:
  - sudo apt-get update
  - sudo apt-get install clang lldb-3.8 libicu-dev libtool libcurl4-openssl-dev libbsd-dev build-essential libssl-dev uuid-dev tzdata libz-dev
  - wget https://swift.org/builds/swift-4.0-release/ubuntu1604/swift-4.0-RELEASE/swift-4.0-RELEASE-ubuntu16.04.tar.gz
  - tar xzvf swift-4.0-RELEASE-ubuntu16.04.tar.gz
  - export PATH=$PWD/swift-4.0-RELEASE-ubuntu16.04/usr/bin:$PATH
  - sudo apt-get install uuid-dev libmysqlclient-dev

script:
  - swift build
