#matrix:
#  include:
#    - env: BUILD="swift build"
#      os: linux
#    - env: BUILD="swift build -Xlinker -L/usr/local/lib" SWIFT_VERSION=swift-4.0-RELEASE
#      os: osx
#  allow_failures:
#    - os: osx
os: linux

language: generic
sudo: required
dist: trusty
#osx_image: xcode9

#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mysql; fi

before_install:
  - sudo apt-get install uuid-dev libmysqlclient-dev -y
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
