matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
       - docker

script:
  - docker pull letsspeak/stock-ci:latest
  - docker run -d letsspeak/stock-ci:latest
  - docker ps -a
  - docker cp . $(docker ps -aq):/var/stock
  - docker ps -a
  - docker exec $(docker ps -aq) bash -c 'OPTIMIZE=1 make deps all'

notifications:
  email:
    on_success: never
    on_failure: always
