version: 0.0
os: linux
files:
  - source: .build/release/stock
    destination: /home/stock
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: root

