version: 2

jobs:
  build:
    docker:
      - image: letsspeak/stock-ci:latest
    steps:
      - checkout
      - run: OPTIMIZE=1 make deps all

  deploy:
    steps:
      - run: docker ps -a

workflows:
  version: 2
  tests:
    jobs:
      - build
      - deploy
        requires:
          - build
#          filters:
#            branches:
#              only: master
