version: 2

jobs:
  build-job:
    docker:
      - image: letsspeak/stock-ci:latest
    steps:
      - checkout
      - run: OPTIMIZE=1 make deps all

  deploy-job:
    steps:
      - run: docker ps -a

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job
          requires:
            - build-job
#          filters:
#            branches:
#              only: master
