version: 2

jobs:
  build-job:
    docker:
      - image: letsspeak/stock-ci:latest
    docker_layer_caching: true
    working_directory: ~/stock
    steps:
      - checkout
      - run: OPTIMIZE=1 make deps all
      - run: pwd
      - run: ls -al
      - persist_to_workspace:
          root: .
          paths: .

  deploy-job:
    machine:
      enabled: true
    docker_layer_caching: true
    working_directory: ~/stock
    steps:
      - checkout
      - attach_workspace:
          at: ~/stock
      - run: pwd
      - run: ls -al

#    steps:
#      - run: docker ps -a

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: react
