version: 2

jobs:
  ubuntu:
    docker:
      - image: letsspeak/stock-ci:latest
    steps:
      - checkout
      - run: OPTIMIZE=1 make deps all

workflows:
  version: 2
  tests:
    jobs:
      - ubuntu
