version: 0.0
os: linux
files:
  - source: stock
    destination: /home/stock
  - source: Config
    destination: /home/stock/Config
  - source: Resources
    destination: /home/stock/Resources
  - source: Public
    destination: /home/stock/Public
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: root

